apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace:
spec:
  replicas: "1"
  template:
    spec:
      containers:
        - name: test-container
          ports:
            - name:
---
apiVersion: v1
kind: Service
metadata:

